[build]
installCommand = "composer install --no-interaction --prefer-dist --optimize-autoloader && npm install && npm run build"

[run]
startCommand = "export APP_KEY=base64:jP21cJxk75i8Fpj5xJ8br/e7Wu/6zv5mrIdoI+Afc2s= && chmod -R 777 storage bootstrap/cache && php artisan migrate --seed --force && php artisan serve --host 0.0.0.0 --port ${PORT:-8080}"
